### ISSUE TITLE
Use Rust Enums

### ISSUE THREAD

**Issue by thedataking** [immunant/rexpat#33]
C2Rust translates C `enum`s to a series of `const`s. We need to Oxidize these.

- [x] `ByteType` enum in `xmltok_impl.h`
- [x] `XML_Status` in `expat.h`
- [x] `XML_Error` in `expat.h`
- [x] `XML_Content_Type` in `expat.h`
- [x] `XML_Content_Quant` in `expat.h`
- [x] `XML_Parsing` in `expat.h`
- [x] `XML_ParamEntityParsing` in `expat.h`
- [x] `XML_FeatureEnum` in `expat.h`

**Comment by ahomescu** [comment]
Make sure the externally-facing enums remain FFI-compatible.

**Comment by thedataking** [comment]
Found a couple of additional enums to convert.
